<?php

namespace Satusehat\Integration\Terminology;

class CompositionTerminology
{
    public array $type = [
        '18842-5' => ['system' => 'http://loinc.org', 'display' => 'Discharge summary'],
        'COM000001' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-type', 'display' => 'Formulir Informasi Kematian Maternal'],
    ];

    public array $category = [
        '11369-6' => ['system' => 'http://loinc.org', 'display' => 'History of Immunization'],
        '11485-0' => ['system' => 'http://loinc.org', 'display' => 'Anesthesia records'],
        '11486-8' => ['system' => 'http://loinc.org', 'display' => 'Chemotherapy records'],
        '11488-4' => ['system' => 'http://loinc.org', 'display' => 'Consult Note'],
        '11506-3' => ['system' => 'http://loinc.org', 'display' => 'Provider-unspecified progress note'],
        '11543-6' => ['system' => 'http://loinc.org', 'display' => 'Nursery records'],
        '15508-5' => ['system' => 'http://loinc.org', 'display' => 'Labor and delivery records'],
        '18726-0' => ['system' => 'http://loinc.org', 'display' => 'Radiology studies (set)'],
        '18761-7' => ['system' => 'http://loinc.org', 'display' => 'Provider-unspecified transfer summary'],
        '18842-5' => ['system' => 'http://loinc.org', 'display' => 'Discharge summary'],
        '26436-6' => ['system' => 'http://loinc.org', 'display' => 'Laboratory Studies (set)'],
        '26441-6' => ['system' => 'http://loinc.org', 'display' => 'Cardiology studies (set)'],
        '26442-4' => ['system' => 'http://loinc.org', 'display' => 'Obstetrical studies (set)'],
        '27895-2' => ['system' => 'http://loinc.org', 'display' => 'Gastroenterology endoscopy studies (set)'],
        '27896-0' => ['system' => 'http://loinc.org', 'display' => 'Pulmonary studies (set)'],
        '27897-8' => ['system' => 'http://loinc.org', 'display' => 'Neuromuscular electrophysiology studies (set)'],
        '27898-6' => ['system' => 'http://loinc.org', 'display' => 'Pathology studies (set)'],
        '28570-0' => ['system' => 'http://loinc.org', 'display' => 'Provider-unspecified procedure note'],
        '28619-5' => ['system' => 'http://loinc.org', 'display' => 'Ophthalmology/optometry studies (set)'],
        '28634-4' => ['system' => 'http://loinc.org', 'display' => 'Miscellaneous studies (set)'],
        '29749-9' => ['system' => 'http://loinc.org', 'display' => 'Dialysis records'],
        '29750-7' => ['system' => 'http://loinc.org', 'display' => 'Neonatal intensive care records'],
        '29751-5' => ['system' => 'http://loinc.org', 'display' => 'Critical care records'],
        '29752-3' => ['system' => 'http://loinc.org', 'display' => 'Perioperative records'],
        '34109-9' => ['system' => 'http://loinc.org', 'display' => 'Evaluation and management note'],
        '34117-2' => ['system' => 'http://loinc.org', 'display' => 'Provider-unspecified, History and physical note'],
        '34121-4' => ['system' => 'http://loinc.org', 'display' => 'Interventional procedure note'],
        '34122-2' => ['system' => 'http://loinc.org', 'display' => 'Pathology procedure note'],
        '34133-9' => ['system' => 'http://loinc.org', 'display' => 'Summarization of episode note'],
        '34140-4' => ['system' => 'http://loinc.org', 'display' => 'Transfer of care referral note'],
        '34748-4' => ['system' => 'http://loinc.org', 'display' => 'Telephone encounter note'],
        '34775-7' => ['system' => 'http://loinc.org', 'display' => 'General surgery Pre-operative evaluation and management note'],
        '47039-3' => ['system' => 'http://loinc.org', 'display' => 'Inpatient Admission history and physical note'],
        '47042-7' => ['system' => 'http://loinc.org', 'display' => 'Counseling note'],
        '47045-0' => ['system' => 'http://loinc.org', 'display' => 'Study report Document'],
        '47046-8' => ['system' => 'http://loinc.org', 'display' => 'Summary of death'],
        '47049-2' => ['system' => 'http://loinc.org', 'display' => 'Non-patient Communication'],
        '57017-6' => ['system' => 'http://loinc.org', 'display' => 'Privacy Policy Organization Document'],
        '57016-8' => ['system' => 'http://loinc.org', 'display' => 'Privacy Policy Acknowledgment Document'],
        '56445-0' => ['system' => 'http://loinc.org', 'display' => 'Medication Summary Document'],
        '53576-5' => ['system' => 'http://loinc.org', 'display' => 'Personal health monitoring report Document'],
        '56447-6' => ['system' => 'http://loinc.org', 'display' => 'Plan of care note'],
        '18748-4' => ['system' => 'http://loinc.org', 'display' => 'Diagnostic imaging study'],
        '11504-8' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation note'],
        '57133-1' => ['system' => 'http://loinc.org', 'display' => 'Referral note'],
        'LP173387-4' => ['system' => 'http://loinc.org', 'display' => 'Administrative note'],
        'LP173388-2' => ['system' => 'http://loinc.org', 'display' => 'Against medical advice note'],
        'LP173389-0' => ['system' => 'http://loinc.org', 'display' => 'Agreement'],
        'LP412176-2' => ['system' => 'http://loinc.org', 'display' => 'Controlled substance agreement'],
        'LP173390-8' => ['system' => 'http://loinc.org', 'display' => 'Certificate'],
        'LP173391-6' => ['system' => 'http://loinc.org', 'display' => 'Birth certificate'],
        'LP173392-4' => ['system' => 'http://loinc.org', 'display' => 'Death certificate'],
        'LP173393-2' => ['system' => 'http://loinc.org', 'display' => 'Evaluation of mental and physical incapacity certificate'],
        'LP267921-7' => ['system' => 'http://loinc.org', 'display' => 'Proof of encounter certificate'],
        'LP173394-0' => ['system' => 'http://loinc.org', 'display' => 'Consent'],
        'LP173395-7' => ['system' => 'http://loinc.org', 'display' => 'Abortion consent'],
        'LP173396-5' => ['system' => 'http://loinc.org', 'display' => 'Anesthesia consent'],
        'LP267939-9' => ['system' => 'http://loinc.org', 'display' => 'Blood or blood product transfusion consent'],
        'LP173397-3' => ['system' => 'http://loinc.org', 'display' => 'Hysterectomy consent'],
        'LP267417-6' => ['system' => 'http://loinc.org', 'display' => 'Long-term opioid therapy for pain consent'],
        'LP173398-1' => ['system' => 'http://loinc.org', 'display' => 'Organ donation consent'],
        'LP173399-9' => ['system' => 'http://loinc.org', 'display' => 'Procedure consent'],
        'LP173400-5' => ['system' => 'http://loinc.org', 'display' => 'Release of information consent'],
        'LP416139-6' => ['system' => 'http://loinc.org', 'display' => 'Research study consent'],
        'LP173401-3' => ['system' => 'http://loinc.org', 'display' => 'Sterilization consent'],
        'LP173402-1' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation consent'],
        'LP173403-9' => ['system' => 'http://loinc.org', 'display' => 'Contract'],
        'LP193873-9' => ['system' => 'http://loinc.org', 'display' => 'Driver license'],
        'LP173404-7' => ['system' => 'http://loinc.org', 'display' => 'Health insurance card'],
        'LP173405-4' => ['system' => 'http://loinc.org', 'display' => 'Health insurance-related form'],
        'LP173406-2' => ['system' => 'http://loinc.org', 'display' => 'Health record cover sheet'],
        'LP173407-0' => ['system' => 'http://loinc.org', 'display' => 'Legal document'],
        'LP200113-1' => ['system' => 'http://loinc.org', 'display' => 'Legal letter'],
        'LP416137-0' => ['system' => 'http://loinc.org', 'display' => 'Portable medical order form'],
        'LP173408-8' => ['system' => 'http://loinc.org', 'display' => 'Power of attorney'],
        'LP248740-5' => ['system' => 'http://loinc.org', 'display' => 'Medical clearance note'],
        'LP181089-6' => ['system' => 'http://loinc.org', 'display' => 'Request'],
        'LP181085-4' => ['system' => 'http://loinc.org', 'display' => 'Prescription request'],
        'LP173409-6' => ['system' => 'http://loinc.org', 'display' => 'Advance directives'],
        'LP173410-4' => ['system' => 'http://loinc.org', 'display' => 'Do not resuscitate'],
        'LP173411-2' => ['system' => 'http://loinc.org', 'display' => 'Rescinded do not resuscitate'],
        'LP173412-0' => ['system' => 'http://loinc.org', 'display' => 'Living will'],
        'LP173413-8' => ['system' => 'http://loinc.org', 'display' => 'Rescinded advance directive'],
        'LP200111-5' => ['system' => 'http://loinc.org', 'display' => 'Checklist'],
        'LP267279-0' => ['system' => 'http://loinc.org', 'display' => 'Discharge checklist'],
        'LP173414-6' => ['system' => 'http://loinc.org', 'display' => 'Diagram'],
        'LP173415-3' => ['system' => 'http://loinc.org', 'display' => 'Flowsheet'],
        'LP181112-6' => ['system' => 'http://loinc.org', 'display' => 'Form'],
        'LP204180-6' => ['system' => 'http://loinc.org', 'display' => 'Mandatory reporting form'],
        'LP416138-8' => ['system' => 'http://loinc.org', 'display' => 'Medical history screening form'],
        'LP416137-0' => ['system' => 'http://loinc.org', 'display' => 'Portable medical order form'],
        'LP181116-7' => ['system' => 'http://loinc.org', 'display' => 'Instructions'],
        'LP181119-1' => ['system' => 'http://loinc.org', 'display' => 'Action plan'],
        'LP173754-5' => ['system' => 'http://loinc.org', 'display' => 'ADHD action plan'],
        'LP420133-3' => ['system' => 'http://loinc.org', 'display' => 'Adrenal insufficiency emergency action plan'],
        'LP173755-2' => ['system' => 'http://loinc.org', 'display' => 'Anaphylaxis action plan'],
        'LP173756-0' => ['system' => 'http://loinc.org', 'display' => 'Asthma action plan'],
        'LP173757-8' => ['system' => 'http://loinc.org', 'display' => 'Autism action plan'],
        'LP173758-6' => ['system' => 'http://loinc.org', 'display' => 'Complex medical conditions action plan'],
        'LP173759-4' => ['system' => 'http://loinc.org', 'display' => 'Cystic fibrosis action plan'],
        'LP173765-1' => ['system' => 'http://loinc.org', 'display' => 'Diabetes type I action plan'],
        'LP173766-9' => ['system' => 'http://loinc.org', 'display' => 'Diabetes type II action plan'],
        'LP173760-2' => ['system' => 'http://loinc.org', 'display' => 'Heart disease action plan'],
        'LP173761-0' => ['system' => 'http://loinc.org', 'display' => 'Inflammatory bowel disease action plan'],
        'LP173762-8' => ['system' => 'http://loinc.org', 'display' => 'Multiple sclerosis action plan'],
        'LP173763-6' => ['system' => 'http://loinc.org', 'display' => 'Muscular dystrophy action plan'],
        'LP173764-4' => ['system' => 'http://loinc.org', 'display' => 'Seizure disorder action plan'],
        'LP173118-3' => ['system' => 'http://loinc.org', 'display' => 'Discharge instructions'],
        'LP173417-9' => ['system' => 'http://loinc.org', 'display' => 'Letter'],
        'LP200113-1' => ['system' => 'http://loinc.org', 'display' => 'Legal letter'],
        'LP204161-6' => ['system' => 'http://loinc.org', 'display' => 'List'],
        'LP181534-1' => ['system' => 'http://loinc.org', 'display' => 'Prescription list'],
        'LP173418-7' => ['system' => 'http://loinc.org', 'display' => 'Note'],
        'LP173419-5' => ['system' => 'http://loinc.org', 'display' => 'Adverse event note'],
        'LP173420-3' => ['system' => 'http://loinc.org', 'display' => 'Alert'],
        'LP181207-4' => ['system' => 'http://loinc.org', 'display' => 'Order'],
        'LP416137-0' => ['system' => 'http://loinc.org', 'display' => 'Portable medical order form'],
        'LP181204-1' => ['system' => 'http://loinc.org', 'display' => 'Prescription'],
        'LP181529-1' => ['system' => 'http://loinc.org', 'display' => 'Prescription for diagnostic or specialist care'],
        'LP181530-9' => ['system' => 'http://loinc.org', 'display' => 'Prescription for durable medical equipment attachment'],
        'LP181190-2' => ['system' => 'http://loinc.org', 'display' => 'Prescription for eyewear'],
        'LP181531-7' => ['system' => 'http://loinc.org', 'display' => 'Prescription for medical equipment or product'],
        'LP181532-5' => ['system' => 'http://loinc.org', 'display' => 'Prescription for medication'],
        'LP181533-3' => ['system' => 'http://loinc.org', 'display' => 'Prescription for rehabilitation'],
        'LP181534-1' => ['system' => 'http://loinc.org', 'display' => 'Prescription list'],
        'LP181231-4' => ['system' => 'http://loinc.org', 'display' => 'Photographic image'],
        'LP173421-1' => ['system' => 'http://loinc.org', 'display' => 'Report'],
        'LP183503-4' => ['system' => 'http://loinc.org', 'display' => 'Case report'],
        'LP183502-6' => ['system' => 'http://loinc.org', 'display' => 'Registry report'],
    ];

    public array $section = [
        '10154-3' => ['system' => 'http://loinc.org', 'display' => 'Chief complaint Narrative - Reported'],
        '10157-6' => ['system' => 'http://loinc.org', 'display' => 'History of family member diseases Narrative'],
        '10160-0' => ['system' => 'http://loinc.org', 'display' => 'History of medication use Narrative'],
        '10164-2' => ['system' => 'http://loinc.org', 'display' => 'History of present illness Narrative'],
        '10183-2' => ['system' => 'http://loinc.org', 'display' => 'Hospital discharge medications Narrative'],
        '10184-0' => ['system' => 'http://loinc.org', 'display' => 'Hospital discharge physical findings Narrative'],
        '10187-3' => ['system' => 'http://loinc.org', 'display' => 'Review of systems Narrative - Reported'],
        '10210-3' => ['system' => 'http://loinc.org', 'display' => 'Physical findings of General status Narrative'],
        '10216-0' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation note fluids Narrative'],
        '10218-6' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation note postoperative diagnosis Narrative'],
        '10223-6' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation note surgical procedure Narrative'],
        '10222-8' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation note surgical complications [interpretation] Narrative'],
        '11329-0' => ['system' => 'http://loinc.org', 'display' => 'History general Narrative - Reported'],
        '11348-0' => ['system' => 'http://loinc.org', 'display' => 'History of past illness Narrative'],
        '11369-6' => ['system' => 'http://loinc.org', 'display' => 'History of immunization Narrative'],
        '57852-6' => ['system' => 'http://loinc.org', 'display' => 'Problem list Narrative - Reported'],
        '11493-4' => ['system' => 'http://loinc.org', 'display' => 'Hospital discharge studies summary Narrative'],
        '11535-2' => ['system' => 'http://loinc.org', 'display' => 'Hospital discharge Dx Narrative'],
        '11537-8' => ['system' => 'http://loinc.org', 'display' => 'Surgical drains Narrative'],
        '18776-5' => ['system' => 'http://loinc.org', 'display' => 'Plan of treatment (narrative)'],
        '18841-7' => ['system' => 'http://loinc.org', 'display' => 'Hospital consultations Document'],
        '29299-5' => ['system' => 'http://loinc.org', 'display' => 'Reason for visit Narrative'],
        '29545-1' => ['system' => 'http://loinc.org', 'display' => 'Physical findings Narrative'],
        '29549-3' => ['system' => 'http://loinc.org', 'display' => 'Medication administered Narrative'],
        '29554-3' => ['system' => 'http://loinc.org', 'display' => 'Procedure Narrative'],
        '29762-2' => ['system' => 'http://loinc.org', 'display' => 'Social history Narrative'],
        '30954-2' => ['system' => 'http://loinc.org', 'display' => 'Relevant diagnostic tests/laboratory data Narrative'],
        '42344-2' => ['system' => 'http://loinc.org', 'display' => 'Discharge diet (narrative)'],
        '42346-7' => ['system' => 'http://loinc.org', 'display' => 'Medications on admission (narrative)'],
        '42348-3' => ['system' => 'http://loinc.org', 'display' => 'Advance directives (narrative)'],
        '42349-1' => ['system' => 'http://loinc.org', 'display' => 'Reason for referral (narrative)'],
        '46240-8' => ['system' => 'http://loinc.org', 'display' => 'History of hospitalizations+History of outpatient visits Narrative'],
        '46241-6' => ['system' => 'http://loinc.org', 'display' => 'Hospital admission diagnosis Narrative - Reported'],
        '46264-8' => ['system' => 'http://loinc.org', 'display' => 'History of medical device use'],
        '47420-5' => ['system' => 'http://loinc.org', 'display' => 'Functional status assessment note'],
        '47519-4' => ['system' => 'http://loinc.org', 'display' => 'History of Procedures Document'],
        '48765-2' => ['system' => 'http://loinc.org', 'display' => 'Allergies and adverse reactions Document'],
        '48768-6' => ['system' => 'http://loinc.org', 'display' => 'Payment sources Document'],
        '51848-0' => ['system' => 'http://loinc.org', 'display' => 'Evaluation note'],
        '55109-3' => ['system' => 'http://loinc.org', 'display' => 'Complications Document'],
        '55122-6' => ['system' => 'http://loinc.org', 'display' => 'Surgical operation note implants Narrative'],
        '59768-2' => ['system' => 'http://loinc.org', 'display' => 'Procedure indications [interpretation] Narrative'],
        '59769-0' => ['system' => 'http://loinc.org', 'display' => 'Postprocedure diagnosis Narrative'],
        '59770-8' => ['system' => 'http://loinc.org', 'display' => 'Procedure estimated blood loss Narrative'],
        '59771-6' => ['system' => 'http://loinc.org', 'display' => 'Procedure implants Narrative'],
        '59772-4' => ['system' => 'http://loinc.org', 'display' => 'Planned procedure Narrative'],
        '59773-2' => ['system' => 'http://loinc.org', 'display' => 'Procedure specimens taken Narrative'],
        '59775-7' => ['system' => 'http://loinc.org', 'display' => 'Procedure disposition Narrative'],
        '59776-5' => ['system' => 'http://loinc.org', 'display' => 'Procedure findings Narrative'],
        '61149-1' => ['system' => 'http://loinc.org', 'display' => 'Objective Narrative'],
        '61150-9' => ['system' => 'http://loinc.org', 'display' => 'Subjective Narrative'],
        '69730-0' => ['system' => 'http://loinc.org', 'display' => 'Instructions'],
        '8648-8' => ['system' => 'http://loinc.org', 'display' => 'Hospital course Narrative'],
        '8653-8' => ['system' => 'http://loinc.org', 'display' => 'Hospital Discharge instructions'],
        '8716-3' => ['system' => 'http://loinc.org', 'display' => 'Vital signs'],
        'COS000001' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Keadaan Saat Masuk'],
        'COS000002' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Kondisi Medis/Faktor Risiko'],
        'COS000003' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Pengambilan Spesimen'],
        'COS000004' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Hasil Pemeriksaan Laboratorium'],
        'COS000005' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Form Keluar'],
        'COS000006' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Hipertensi'],
        'COS000007' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Obesitas'],
        'COS000008' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Penyakit Jantung'],
        'COS000009' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Diabetes Melitus'],
        'COS000010' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Stroke'],
        'COS000011' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Asam Urat'],
        'COS000012' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Kanker'],
        'COS000013' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Thalassemia'],
        'COS000014' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi dini PPOK'],
        'COS000015' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Gangguan Penglihatan'],
        'COS000016' => ['system' => 'http://terminology.kemkes.go.id/CodeSystem/composition-section', 'display' => 'Deteksi Dini Gangguan Pendengaran'],
        'TK000002' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Episode Perawatan'],
        'TK000007' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Pemeriksaan Fisik'],
        'TK000003' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Anamnesis'],
        'TK000044' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Status Oftalmologi'],
        'TK000004' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Diagnosis'],
        'TK000005' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Tindakan/Prosedur Medis'],
        'TK000009' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Hasil Pemeriksaan Penunjang'],
        'TK000013' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Obat'],
        'TK000045' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Peresepan Kacamata'],
        '97667-0' => ['system' => 'http://loinc.org', 'display' => 'Emergency medicine Emergency department Initial evaluation note'],
        'TK000129' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Skrining'],
        'TK000138' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Status Audiologi'],
        'TK000139' => ['system' => 'http://terminology.kemkes.go.id', 'display' => 'Akhir Pengobatan Telinga'],
    ];
}
