<?php

namespace Satusehat\Integration\Terminology;

class MedicationTerminology
{
    public array $medication_form = array(
        "BS001" => "Aerosol Foam",
        "BS002" => "Aerosol Metered Dose",
        "BS003" => "Aerosol Spray",
        "BS004" => "Oral Spray",
        "BS005" => "Buscal Spray",
        "BS006" => "Transdermal Spray",
        "BS007" => "Topical Spray",
        "BS008" => "Serbuk Spray",
        "BS009" => "Eliksir",
        "BS010" => "Emulsi",
        "BS011" => "Enema",
        "BS012" => "Gas",
        "BS013" => "Gel",
        "BS014" => "Gel Mata",
        "BS015" => "Granul Effervescent",
        "BS016" => "Granula",
        "BS017" => "Intra Uterine Device (IUD)",
        "BS018" => "Implant",
        "BS019" => "Kapsul",
        "BS020" => "Kapsul Lunak",
        "BS021" => "Kapsul Pelepasan Lambat",
        "BS022" => "Kaplet",
        "BS023" => "Kaplet Salut Selaput",
        "BS024" => "Kaplet Salut Enterik",
        "BS025" => "Kaplet Salut Gula",
        "BS026" => "Kaplet Pelepasan Lambat",
        "BS027" => "Kaplet Pelepasan Cepat",
        "BS028" => "Kaplet Kunyah",
        "BS029" => "Kaplet Kunyah Salut Selaput",
        "BS030" => "Krim",
        "BS031" => "Krim Lemak",
        "BS032" => "Larutan",
        "BS033" => "Larutan Inhalasi",
        "BS034" => "Larutan Injeksi",
        "BS035" => "Infus",
        "BS036" => "Obat Kumur",
        "BS037" => "Ovula",
        "BS038" => "Pasta",
        "BS039" => "Pil",
        "BS040" => "Patch",
        "BS041" => "Pessary",
        "BS042" => "Salep",
        "BS043" => "Salep Mata",
        "BS044" => "Sampo",
        "BS045" => "Semprot Hidung",
        "BS046" => "Serbuk Aerosol",
        "BS047" => "Serbuk Oral",
        "BS048" => "Serbuk Inhaler",
        "BS049" => "Serbuk Injeksi",
        "BS050" => "Serbuk Injeksi Liofilisasi",
        "BS051" => "Serbuk Infus",
        "BS052" => "Serbuk Obat Luar / Serbuk Tabur",
        "BS053" => "Serbuk Steril",
        "BS054" => "Serbuk Effervescent",
        "BS055" => "Sirup",
        "BS056" => "Sirup Kering",
        "BS057" => "Sirup Kering Pelepasan Lambat",
        "BS058" => "Subdermal Implants",
        "BS059" => "Supositoria",
        "BS060" => "Suspensi",
        "BS061" => "Suspensi Injeksi",
        "BS062" => "Suspensi / Cairan Obat Luar",
        "BS063" => "Cairan Steril",
        "BS064" => "Cairan Mata",
        "BS065" => "Cairan Diagnostik",
        "BS066" => "Tablet",
        "BS067" => "Tablet Effervescent",
        "BS068" => "Tablet Hisap",
        "BS069" => "Tablet Kunyah",
        "BS070" => "Tablet Pelepasan Cepat",
        "BS071" => "Tablet Pelepasan Lambat",
        "BS072" => "Tablet Disintegrasi Oral",
        "BS073" => "Tablet Dispersibel",
        "BS074" => "Tablet Cepat Larut",
        "BS075" => "Tablet Salut Gula",
        "BS076" => "Tablet Salut Enterik",
        "BS077" => "Tablet Salut Selaput",
        "BS078" => "Tablet Sublingual",
        "BS079" => "Tablet Sublingual Pelepasan Lambat",
        "BS080" => "Tablet Vaginal",
        "BS081" => "Tablet Lapis",
        "BS082" => "Tablet Lapis Lepas Lambat",
        "BS083" => "Chewing Gum",
        "BS084" => "Tetes Mata",
        "BS085" => "Tetes Hidung",
        "BS086" => "Tetes Telinga",
        "BS087" => "Tetes Oral (Oral Drops)",
        "BS088" => "Tetes Mata Dan Telinga",
        "BS089" => "Transdermal",
        "BS090" => "Transdermal Urethral",
        "BS091" => "Tulle/Plester Obat",
        "BS092" => "Vaginal Cream",
        "BS093" => "Vaginal Gel",
        "BS094" => "Vaginal Douche",
        "BS095" => "Vaginal Ring",
        "BS096" => "Vaginal Tissue",
        "BS097" => "Suspensi Inhalasi",
        "MF000001" => "Orodispersible Film"
    );

    public array $drug_form = array(
        "APPFUL" => array("display" => "Applicatorful", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DROP" => array("display" => "Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "NDROP" => array("display" => "Nasal Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OPDROP" => array("display" => "Ophthalmic Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORDROP" => array("display" => "Oral Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OTDROP" => array("display" => "Otic Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PUFF" => array("display" => "Puff", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SCOOP" => array("display" => "Scoops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SPRY" => array("display" => "Sprays", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_DispensableDrugForm" => array("display" => "DispensableDrugForm", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_GasDrugForm" => array("display" => "GasDrugForm", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "GASINHL" => array("display" => "Gas for Inhalation", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_GasLiquidMixture" => array("display" => "GasLiquidMixture", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "AER" => array("display" => "Aerosol", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "BAINHL" => array("display" => "Breath Activated Inhaler", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "INHLSOL" => array("display" => "Inhalant Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "MDINHL" => array("display" => "Metered Dose Inhaler", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "NASSPRY" => array("display" => "Nasal Spray", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DERMSPRY" => array("display" => "Dermal Spray", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "FOAM" => array("display" => "Foam", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "FOAMAPL" => array("display" => "Foam with Applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECFORM" => array("display" => "Rectal foam", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGFOAM" => array("display" => "Vaginal foam", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGFOAMAPL" => array("display" => "Vaginal foam with applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECSPRY" => array("display" => "Rectal Spray", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGSPRY" => array("display" => "Vaginal Spray", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_GasSolidSpray" => array("display" => "GasSolidSpray", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "INHL" => array("display" => "Inhalant", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "BAINHLPWD" => array("display" => "Breath Activated Powder Inhaler", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "INHLPWD" => array("display" => "Inhalant Powder", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "MDINHLPWD" => array("display" => "Metered Dose Powder Inhaler", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "NASINHL" => array("display" => "Nasal Inhalant", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORINHL" => array("display" => "Oral Inhalant", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PWDSPRY" => array("display" => "Powder Spray", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SPRYADAPT" => array("display" => "Spray with Adaptor", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_Liquid" => array("display" => "Liquid", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "LIQCLN" => array("display" => "Liquid Cleanser", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "LIQSOAP" => array("display" => "Medicated Liquid Soap", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SHMP" => array("display" => "Shampoo", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OIL" => array("display" => "Oil", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPOIL" => array("display" => "Topical Oil", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SOL" => array("display" => "Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "IPSOL" => array("display" => "Intraperitoneal Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "IRSOL" => array("display" => "Irrigation Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DOUCHE" => array("display" => "Douche", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ENEMA" => array("display" => "Enema", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OPIRSOL" => array("display" => "Ophthalmic Irrigation Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "IVSOL" => array("display" => "Intravenous Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORALSOL" => array("display" => "Oral Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ELIXIR" => array("display" => "Elixir", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RINSE" => array("display" => "Mouthwash/Rinse", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SYRUP" => array("display" => "Syrup", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORDROP" => array("display" => "Oral Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECSOL" => array("display" => "Rectal Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPSOL" => array("display" => "Topical Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "LIN" => array("display" => "Liniment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "MUCTOPSOL" => array("display" => "Mucous Membrane Topical Solution", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TINCTURE" => array("display" => "Tincture", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DROP" => array("display" => "Drops", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_LiquidLiquidEmulsion" => array("display" => "LiquidLiquidEmulsion", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CRM" => array("display" => "Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "NASCRM" => array("display" => "Nasal Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OPCRM" => array("display" => "Ophthalmic Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORCRM" => array("display" => "Oral Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OTCRM" => array("display" => "Otic Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECCRM" => array("display" => "Rectal Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPCRM" => array("display" => "Topical Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGCRM" => array("display" => "Vaginal Cream", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGCRMAPL" => array("display" => "Vaginal Cream with Applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "LTN" => array("display" => "Lotion", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPLTN" => array("display" => "Topical Lotion", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OINT" => array("display" => "Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "NASOINT" => array("display" => "Nasal Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OINTAPL" => array("display" => "Ointment with Applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OPOINT" => array("display" => "Ophthalmic Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OTOINT" => array("display" => "Otic Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECOINT" => array("display" => "Rectal Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPOINT" => array("display" => "Topical Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGOINT" => array("display" => "Vaginal Ointment", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGOINAPPL" => array("display" => "Vaginal Ointment with Applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_LiquidSolidSuspension" => array("display" => "LiquidSolidSuspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "GEL" => array("display" => "Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "GELAPL" => array("display" => "Gel with Applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "NASGEL" => array("display" => "Nasal Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OPGEL" => array("display" => "Ophthalmic Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OTGEL" => array("display" => "Otic Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPGEL" => array("display" => "Topical Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "URETHGEL" => array("display" => "Urethral Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGGEL" => array("display" => "Vaginal Gel", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VGELAPL" => array("display" => "Vaginal Gel with Applicator", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PASTE" => array("display" => "Paste", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PUD" => array("display" => "Pudding", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPASTE" => array("display" => "Toothpaste", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SUSP" => array("display" => "Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ITSUSP" => array("display" => "Intrathecal Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OPSUSP" => array("display" => "Ophthalmic Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORSUSP" => array("display" => "Oral Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERSUSP" => array("display" => "Extended-Release Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERSUSP12" => array("display" => "12 Hour Extended-Release Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERSUSP24" => array("display" => "24 Hour Extended Release Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "OTSUSP" => array("display" => "Otic Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECSUSP" => array("display" => "Rectal Suspension", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "_SolidDrugForm" => array("display" => "Solid Drug Form", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "BAR" => array("display" => "Bar", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "BARSOAP" => array("display" => "Bar Soap", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "MEDBAR" => array("display" => "Medicated Bar Soap", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CHEWBAR" => array("display" => "Chewable Bar", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "BEAD" => array("display" => "Beads", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CAKE" => array("display" => "Cake", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CEMENT" => array("display" => "Cement", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CRYS" => array("display" => "Crystals", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DISK" => array("display" => "Disk", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "FLAKE" => array("display" => "Flakes", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "GRAN" => array("display" => "Granules", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "GUM" => array("display" => "Chewing Gum", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PAD" => array("display" => "Pad", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "MEDPAD" => array("display" => "Medicated Pad", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PATCH" => array("display" => "Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPATCH" => array("display" => "Transdermal Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPATH16" => array("display" => "16 Hour Transdermal Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPATH24" => array("display" => "24 Hour Transdermal Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPATH2WK" => array("display" => "Biweekly Transdermal Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPATH72" => array("display" => "72 Hour Transdermal Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TPATHWK" => array("display" => "Weekly Transdermal Patch", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PELLET" => array("display" => "Pellet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "PILL" => array("display" => "Pill", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CAP" => array("display" => "Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORCAP" => array("display" => "Oral Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ENTCAP" => array("display" => "Enteric Coated Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERECAP" => array("display" => "Extended Release Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERCAP" => array("display" => "Extended Release Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERCAP12" => array("display" => "12 Hour Extended Release Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERCAP24" => array("display" => "24 Hour Extended Release Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERECCAP" => array("display" => "Extended Release Enteric Coated Capsule", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERTAB" => array("display" => "Extended Release Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TAB" => array("display" => "Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORTAB" => array("display" => "Oral Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "BUCTAB" => array("display" => "Buccal Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SRBUCTAB" => array("display" => "Sustained Release Buccal Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CAPLET" => array("display" => "Caplet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CHEWTAB" => array("display" => "Chewable Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "CPTAB" => array("display" => "Coated Particles Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DISINTAB" => array("display" => "Disintegrating Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "DRTAB" => array("display" => "Delayed Release Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ECTAB" => array("display" => "Enteric Coated Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERECTAB" => array("display" => "Extended Release Enteric Coated Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERTAB" => array("display" => "Extended Release Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERTAB12" => array("display" => "12 Hour Extended Release Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ERTAB24" => array("display" => "24 Hour Extended Release Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "ORTROCHE" => array("display" => "Lozenge/Oral Troche", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SLTAB" => array("display" => "Sublingual Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGTAB" => array("display" => "Vaginal Tablet", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "POWD" => array("display" => "Powder", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "TOPPWD" => array("display" => "Topical Powder", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECPWD" => array("display" => "Rectal Powder", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGPWD" => array("display" => "Vaginal Powder", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SUPP" => array("display" => "Suppository", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "RECSUPP" => array("display" => "Rectal Suppository", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "URETHSUPP" => array("display" => "Urethral suppository", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "VAGSUPP" => array("display" => "Vaginal Suppository", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "SWAB" => array("display" => "Swab", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "MEDSWAB" => array("display" => "Medicated swab", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "WAFER" => array("display" => "Wafer", "system" => "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"),
        "EMULSION" => array("display" => "Emulsion", "system" => "http://snomed.info/sct"),
        "GAS" => array("display" => "Gas", "system" => "http://snomed.info/sct"),
        "INTRAUTERINE" => array("display" => "Intrauterine dose form", "system" => "http://snomed.info/sct"),
        "IMPLANT" => array("display" => "Implant", "system" => "http://snomed.info/sct"),
        "PESSARY" => array("display" => "Pessary", "system" => "http://snomed.info/sct"),
        "PROLONGEDRELEASE" => array("display" => "Prolonged-release", "system" => "http://snomed.info/sct"),
        "EFFERVESCENT" => array("display" => "Effervescent tablet", "system" => "http://snomed.info/sct"),
        "TABSUSPENSION" => array("display" => "Tablet for oral suspension", "system" => "http://snomed.info/sct"),
        "TABORAL" => array("display" => "Tablet for conventional release oral solution", "system" => "http://snomed.info/sct"),
        "FILMCOATED" => array("display" => "Film-coated tablet", "system" => "http://snomed.info/sct"),
        "IMPREGDRESSING" => array("display" => "Impregnated dressing", "system" => "http://snomed.info/sct"),
        "PROLONGEDVAGINAL" => array("display" => "Prolonged-release vaginal ring", "system" => "http://snomed.info/sct"),
        "VAGINALDOSE" => array("display" => "Vaginal dose form", "system" => "http://snomed.info/sct")
    );

    public array $medicationrequest_status_reason = array(
        "altchoice" => "Try another treatment first",
        "clarif" => "Prescription requires clarification",
        "drughigh" => "Drug level too high",
        "hospadm" => "Admission to hospital",
        "labint" => "Lab interference issues",
        "non-avail" => "Patient not available",
        "preg" => "Parent is pregnant/breast feeding",
        "salg" => "Allergy",
        "sddi" => "Drug interacts with another drug",
        "sdupther" => "Duplicate therapy",
        "sintol" => "Suspected intolerance",
        "surg" => "Patient scheduled for surgery",
        "washout" => "Waiting for old drug to wash out"
    );

    public array $medicationrequest_category = array(
        "inpatient" => "Inpatient",
        "outpatient" => "Outpatient",
        "community" => "Community",
        "discharge" => "Discharge"
    );

    public array $course_of_therapy_type = array(
        "continuous" => "Continuous long term therapy",
        "acute" => "Short course (acute) therapy",
        "seasonal" => "Seasonal",
    );

    public array $time_interval = array(
        "ms" => "milliseconds",
        "s" => "seconds",
        "min" => "minutes",
        "h" => "hours",
        "d" => "days",
        "wk" => "weeks",
        "mo" => "months",
        "a" => "years",
    );

    public array $substitution_reason = array(
        "E" => "equivalent",
        "EC" => "equivalent composition",
        "BC" => "brand composition",
        "G" => "generic composition",
        "TE" => "therapeutic equivalence",
        "TB" => "therapeutic brand",
        "TG" => "therapeutic generic",
        "F" => "formulary",
        "N" => "none",
    );

    public array $timing = array(
        "BID" => "twice a day",
        "TID" => "three times a day",
        "QID" => "four times a day",
        "AM" => "morning",
        "PM" => "evening",
        "QOD" => "every other day",
        "Q1H" => "every hour",
        "Q2H" => "every 2 hours",
        "Q3H" => "every 3 hours",
        "Q4H" => "every 4 hours",
        "Q6H" => "every 6 hours",
        "Q8H" => "every 8 hours",
        "BED" => "bedtime",
        "WK" => "weekly",
        "MO" => "monthly",
    );

    public array $route_snomed = array(
        697971008 => "Arteriovenous fistula route",
        420254004 => "Body cavity route",
        54471007 => "Buccal route",
        417070009 => "Caudal route",
        418162004 => "Colostomy route",
        446105004 => "Conjunctival route",
        448598008 => "Cutaneous route",
        372449004 => "Dental route",
        447964005 => "Digestive tract route",
        372450004 => "Endocervical route",
        372451000 => "Endosinusial route",
        372452007 => "Endotracheopulmonary route",
        417985001 => "Enteral route",
        404820008 => "Epidural route",
        764723001 => "Epilesional route",
        420163009 => "Esophagostomy route",
        372453002 => "Extra-amniotic route",
        766790006 => "Extracorporeal hemodialysis route",
        714743009 => "Extracorporeal route",
        418743005 => "Fistula route",
        418136008 => "Gastro-intestinal stoma route",
        372454008 => "Gastroenteral route",
        127490009 => "Gastrostomy route",
        372457001 => "Gingival route",
        419954003 => "Ileostomy route",
        718329006 => "Infiltration route",
        429817007 => "Interstitial route",
        58731000052100 => "Intestinal route",
        58100008 => "Intra-arterial route",
        12130007 => "Intra-articular route",
        419396008 => "Intraabdominal route",
        372458006 => "Intraamniotic route",
        404819002 => "Intrabiliary route",
        419778001 => "Intrabronchial route",
        372459003 => "Intrabursal route",
        418821007 => "Intracameral route",
        372460008 => "Intracardiac route",
        418331006 => "Intracartilaginous route",
        1078280005 => "Intracatheter instillation route",
        372461007 => "Intracavernous route",
        446540005 => "Intracerebral route",
        420719007 => "Intracerebroventricular route",
        372462000 => "Intracervical route",
        58761000052107 => "Intracholangiopancreatic route",
        418892005 => "Intracisternal route",
        448492006 => "Intracolonic route",
        418608002 => "Intracorneal route",
        418287000 => "Intracoronal route",
        372463005 => "Intracoronary route",
        1259221004 => "Intracorporus cavernosum route",
        418987007 => "Intracranial route",
        372464004 => "Intradermal route",
        876824003 => "Intradialytic route",
        372465003 => "Intradiscal route",
        417989007 => "Intraductal route",
        418887008 => "Intraduodenal route",
        445756007 => "Intradural route",
        446407004 => "Intraepicardial route",
        448077001 => "Intraepidermal route",
        445752009 => "Intraesophageal route",
        445768003 => "Intragastric route",
        445754005 => "Intragingival route",
        58751000052109 => "Intraglandular route",
        445941009 => "Intrahepatic route",
        447026006 => "Intraileal route",
        448491004 => "Intrajejunal route",
        372466002 => "Intralesional route",
        445913005 => "Intralingual route",
        37737002 => "Intraluminal route",
        372467006 => "Intralymphatic route",
        447121004 => "Intramammary route",
        60213007 => "Intramedullary route",
        445767008 => "Intrameningeal route",
        711378007 => "Intramural route",
        78421000 => "Intramuscular route",
        418133000 => "Intramyometrial route",
        711360002 => "Intraneural route",
        372468001 => "Intraocular route",
        417255000 => "Intraosseous route",
        419631009 => "Intraovarian route",
        445771006 => "Intrapericardial route",
        38239002 => "Intraperitoneal route",
        372469009 => "Intrapleural route",
        58771000052103 => "Intraportal route",
        419810008 => "Intraprostatic route",
        420201002 => "Intrapulmonary route",
        419231003 => "Intrasinal route",
        418418000 => "Intraspinal route",
        372470005 => "Intrasternal route",
        418877009 => "Intrasynovial route",
        418586008 => "Intratendinous route",
        418947002 => "Intratesticular route",
        72607000 => "Intrathecal route",
        417950001 => "Intrathoracic route",
        404818005 => "Intratracheal route",
        447122006 => "Intratumor route",
        418091004 => "Intratympanic route",
        62226000 => "Intrauterine route",
        445755006 => "Intravascular route",
        418114005 => "Intravenous central route",
        419993007 => "Intravenous peripheral route",
        47625008 => "Intravenous route",
        420287000 => "Intraventricular route - cardiac",
        372471009 => "Intravesical route",
        418401004 => "Intravitreal route",
        127491008 => "Jejunostomy route",
        420185003 => "Laryngeal route",
        447081004 => "Lower respiratory tract route",
        420204005 => "Mucous fistula route",
        46713006 => "Nasal route",
        420218003 => "Nasoduodenal route",
        127492001 => "Nasogastric route",
        418730005 => "Nasojejunal route",
        372472002 => "Ocular route",
        54485002 => "Ophthalmic route",
        26643006 => "Oral route",
        418441008 => "Orogastric route",
        372473007 => "Oromucosal route",
        418664002 => "Oropharyngeal route",
        10547007 => "Otic route",
        418851001 => "Paracervical route",
        419165009 => "Paravertebral route",
        428191002 => "Percutaneous route",
        372474001 => "Periarticular route",
        418722009 => "Peribulbar route",
        447080003 => "Peridural route",
        372475000 => "Perineural route",
        447052000 => "Periodontal route",
        420047004 => "Periosteal route",
        419762003 => "Peritendinous route",
        58811000052103 => "Peritumoral route",
        418204005 => "Periurethral route",
        58821000052106 => "Posterior juxtascleral route",
        37161004 => "Rectal route",
        447694001 => "Respiratory tract route",
        418321004 => "Retrobulbar route",
        372476004 => "Subconjunctival route",
        34206005 => "Subcutaneous route",
        419601003 => "Subgingival route",
        66621000052103 => "Sublabial route",
        1611000175109 => "Sublesional route",
        37839007 => "Sublingual route",
        419874009 => "Submucosal route",
        416174007 => "Suborbital route",
        58831000052108 => "Subretinal route",
        419320008 => "Subtendinous route",
        1254769004 => "Suprachoroidal route",
        419894000 => "Surgical cavity route",
        418813001 => "Surgical drain route",
        6064005 => "Topical route",
        419243002 => "Transcervical route",
        45890007 => "Transdermal route",
        446435000 => "Transendocardial route",
        404815008 => "Transmucosal route",
        446442000 => "Transplacental route",
        447229005 => "Transtracheal route",
        447227007 => "Transtympanic route",
        418511008 => "Transurethral route",
        419021003 => "Tumor cavity route",
        419684008 => "Ureteral route",
        90028008 => "Urethral route",
        420168000 => "Urostomy route",
        16857009 => "Vaginal route",
    );

    public array $route = array(
        "implant" => "Implant",
        "Inhal" => "Inhalation",
        "Instill" => "Instillation",
        "N" => "Nasal",
        "O" => "Oral",
        "P" => "Parenteral",
        "R" => "Rectal",
        "SL" => "Sublingual/Buccal/Oromucosal",
        "TD" => "Transdermal",
        "V" => "Vaginal",
        "Inhal.powder" => "Inhalation Powder",
        "Inhal.aerosol" => "Inhalation Aerosol",
        "Inhal.solution" => "Inhalation Solution",
        "urethral" => "Urethral",
        "TD patch" => "Transdermal Patch",
        "intravesical" => "Intravesical",
        "Instill.solution" => "Instillation Solution",
        "lamella" => "Lamella",
        "oral aerosol" => "Oral Aerosol",
        "s.c. implant" => "S.C. Implant",
        "ocular" => "Ocular",
        "otic" => "Otic",
        "cutaneous" => "Cutaneous",
        "inj.subcutaneous" => "Injection Subcutaneous",
        "inj.intramuscular" => "Injection Intramuscular",
        "inj.intravenous" => "Injection Intravenous",
        "inj.intrathecal" => "Injection Intrathecal",
        "Chewing Gum" => "Chewing Gum",
        "ointment" => "Ointment",
        "stomatologic" => "Stomatologic"
    );

    public function __construct()
    {
        $this->medication_form = $this->medication_form;
        $this->drug_form = $this->drug_form;
        $this->medicationrequest_status_reason = $this->medicationrequest_status_reason;
        $this->medicationrequest_category = $this->medicationrequest_category;
        $this->course_of_therapy_type = $this->course_of_therapy_type;
        $this->time_interval = $this->time_interval;
        $this->substitution_reason = $this->substitution_reason;
        $this->route = $this->route;
        $this->timing = $this->timing;
    }

}
