<?php

namespace Satusehat\Integration\Terminology;

class MedicationTerminology
{
    public array $medication_form = [
        'BS001' => 'Aerosol Foam',
        'BS002' => 'Aerosol Metered Dose',
        'BS003' => 'Aerosol Spray',
        'BS004' => 'Oral Spray',
        'BS005' => 'Buscal Spray',
        'BS006' => 'Transdermal Spray',
        'BS007' => 'Topical Spray',
        'BS008' => 'Serbuk Spray',
        'BS009' => 'Eliksir',
        'BS010' => 'Emulsi',
        'BS011' => 'Enema',
        'BS012' => 'Gas',
        'BS013' => 'Gel',
        'BS014' => 'Gel Mata',
        'BS015' => 'Granul Effervescent',
        'BS016' => 'Granula',
        'BS017' => 'Intra Uterine Device (IUD)',
        'BS018' => 'Implant',
        'BS019' => 'Kapsul',
        'BS020' => 'Kapsul Lunak',
        'BS021' => 'Kapsul Pelepasan Lambat',
        'BS022' => 'Kaplet',
        'BS023' => 'Kaplet Salut Selaput',
        'BS024' => 'Kaplet Salut Enterik',
        'BS025' => 'Kaplet Salut Gula',
        'BS026' => 'Kaplet Pelepasan Lambat',
        'BS027' => 'Kaplet Pelepasan Cepat',
        'BS028' => 'Kaplet Kunyah',
        'BS029' => 'Kaplet Kunyah Salut Selaput',
        'BS030' => 'Krim',
        'BS031' => 'Krim Lemak',
        'BS032' => 'Larutan',
        'BS033' => 'Larutan Inhalasi',
        'BS034' => 'Larutan Injeksi',
        'BS035' => 'Infus',
        'BS036' => 'Obat Kumur',
        'BS037' => 'Ovula',
        'BS038' => 'Pasta',
        'BS039' => 'Pil',
        'BS040' => 'Patch',
        'BS041' => 'Pessary',
        'BS042' => 'Salep',
        'BS043' => 'Salep Mata',
        'BS044' => 'Sampo',
        'BS045' => 'Semprot Hidung',
        'BS046' => 'Serbuk Aerosol',
        'BS047' => 'Serbuk Oral',
        'BS048' => 'Serbuk Inhaler',
        'BS049' => 'Serbuk Injeksi',
        'BS050' => 'Serbuk Injeksi Liofilisasi',
        'BS051' => 'Serbuk Infus',
        'BS052' => 'Serbuk Obat Luar / Serbuk Tabur',
        'BS053' => 'Serbuk Steril',
        'BS054' => 'Serbuk Effervescent',
        'BS055' => 'Sirup',
        'BS056' => 'Sirup Kering',
        'BS057' => 'Sirup Kering Pelepasan Lambat',
        'BS058' => 'Subdermal Implants',
        'BS059' => 'Supositoria',
        'BS060' => 'Suspensi',
        'BS061' => 'Suspensi Injeksi',
        'BS062' => 'Suspensi / Cairan Obat Luar',
        'BS063' => 'Cairan Steril',
        'BS064' => 'Cairan Mata',
        'BS065' => 'Cairan Diagnostik',
        'BS066' => 'Tablet',
        'BS067' => 'Tablet Effervescent',
        'BS068' => 'Tablet Hisap',
        'BS069' => 'Tablet Kunyah',
        'BS070' => 'Tablet Pelepasan Cepat',
        'BS071' => 'Tablet Pelepasan Lambat',
        'BS072' => 'Tablet Disintegrasi Oral',
        'BS073' => 'Tablet Dispersibel',
        'BS074' => 'Tablet Cepat Larut',
        'BS075' => 'Tablet Salut Gula',
        'BS076' => 'Tablet Salut Enterik',
        'BS077' => 'Tablet Salut Selaput',
        'BS078' => 'Tablet Sublingual',
        'BS079' => 'Tablet Sublingual Pelepasan Lambat',
        'BS080' => 'Tablet Vaginal',
        'BS081' => 'Tablet Lapis',
        'BS082' => 'Tablet Lapis Lepas Lambat',
        'BS083' => 'Chewing Gum',
        'BS084' => 'Tetes Mata',
        'BS085' => 'Tetes Hidung',
        'BS086' => 'Tetes Telinga',
        'BS087' => 'Tetes Oral (Oral Drops)',
        'BS088' => 'Tetes Mata Dan Telinga',
        'BS089' => 'Transdermal',
        'BS090' => 'Transdermal Urethral',
        'BS091' => 'Tulle/Plester Obat',
        'BS092' => 'Vaginal Cream',
        'BS093' => 'Vaginal Gel',
        'BS094' => 'Vaginal Douche',
        'BS095' => 'Vaginal Ring',
        'BS096' => 'Vaginal Tissue',
        'BS097' => 'Suspensi Inhalasi',
        'MF000001' => 'Orodispersible Film',
    ];

    public array $drug_form = [
        'APPFUL' => ['display' => 'Applicatorful', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DROP' => ['display' => 'Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'NDROP' => ['display' => 'Nasal Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OPDROP' => ['display' => 'Ophthalmic Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORDROP' => ['display' => 'Oral Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OTDROP' => ['display' => 'Otic Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PUFF' => ['display' => 'Puff', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SCOOP' => ['display' => 'Scoops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SPRY' => ['display' => 'Sprays', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_DispensableDrugForm' => ['display' => 'DispensableDrugForm', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_GasDrugForm' => ['display' => 'GasDrugForm', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'GASINHL' => ['display' => 'Gas for Inhalation', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_GasLiquidMixture' => ['display' => 'GasLiquidMixture', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'AER' => ['display' => 'Aerosol', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'BAINHL' => ['display' => 'Breath Activated Inhaler', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'INHLSOL' => ['display' => 'Inhalant Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'MDINHL' => ['display' => 'Metered Dose Inhaler', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'NASSPRY' => ['display' => 'Nasal Spray', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DERMSPRY' => ['display' => 'Dermal Spray', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'FOAM' => ['display' => 'Foam', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'FOAMAPL' => ['display' => 'Foam with Applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECFORM' => ['display' => 'Rectal foam', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGFOAM' => ['display' => 'Vaginal foam', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGFOAMAPL' => ['display' => 'Vaginal foam with applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECSPRY' => ['display' => 'Rectal Spray', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGSPRY' => ['display' => 'Vaginal Spray', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_GasSolidSpray' => ['display' => 'GasSolidSpray', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'INHL' => ['display' => 'Inhalant', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'BAINHLPWD' => ['display' => 'Breath Activated Powder Inhaler', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'INHLPWD' => ['display' => 'Inhalant Powder', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'MDINHLPWD' => ['display' => 'Metered Dose Powder Inhaler', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'NASINHL' => ['display' => 'Nasal Inhalant', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORINHL' => ['display' => 'Oral Inhalant', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PWDSPRY' => ['display' => 'Powder Spray', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SPRYADAPT' => ['display' => 'Spray with Adaptor', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_Liquid' => ['display' => 'Liquid', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'LIQCLN' => ['display' => 'Liquid Cleanser', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'LIQSOAP' => ['display' => 'Medicated Liquid Soap', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SHMP' => ['display' => 'Shampoo', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OIL' => ['display' => 'Oil', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPOIL' => ['display' => 'Topical Oil', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SOL' => ['display' => 'Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'IPSOL' => ['display' => 'Intraperitoneal Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'IRSOL' => ['display' => 'Irrigation Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DOUCHE' => ['display' => 'Douche', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ENEMA' => ['display' => 'Enema', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OPIRSOL' => ['display' => 'Ophthalmic Irrigation Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'IVSOL' => ['display' => 'Intravenous Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORALSOL' => ['display' => 'Oral Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ELIXIR' => ['display' => 'Elixir', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RINSE' => ['display' => 'Mouthwash/Rinse', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SYRUP' => ['display' => 'Syrup', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORDROP' => ['display' => 'Oral Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECSOL' => ['display' => 'Rectal Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPSOL' => ['display' => 'Topical Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'LIN' => ['display' => 'Liniment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'MUCTOPSOL' => ['display' => 'Mucous Membrane Topical Solution', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TINCTURE' => ['display' => 'Tincture', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DROP' => ['display' => 'Drops', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_LiquidLiquidEmulsion' => ['display' => 'LiquidLiquidEmulsion', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CRM' => ['display' => 'Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'NASCRM' => ['display' => 'Nasal Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OPCRM' => ['display' => 'Ophthalmic Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORCRM' => ['display' => 'Oral Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OTCRM' => ['display' => 'Otic Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECCRM' => ['display' => 'Rectal Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPCRM' => ['display' => 'Topical Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGCRM' => ['display' => 'Vaginal Cream', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGCRMAPL' => ['display' => 'Vaginal Cream with Applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'LTN' => ['display' => 'Lotion', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPLTN' => ['display' => 'Topical Lotion', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OINT' => ['display' => 'Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'NASOINT' => ['display' => 'Nasal Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OINTAPL' => ['display' => 'Ointment with Applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OPOINT' => ['display' => 'Ophthalmic Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OTOINT' => ['display' => 'Otic Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECOINT' => ['display' => 'Rectal Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPOINT' => ['display' => 'Topical Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGOINT' => ['display' => 'Vaginal Ointment', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGOINAPPL' => ['display' => 'Vaginal Ointment with Applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_LiquidSolidSuspension' => ['display' => 'LiquidSolidSuspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'GEL' => ['display' => 'Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'GELAPL' => ['display' => 'Gel with Applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'NASGEL' => ['display' => 'Nasal Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OPGEL' => ['display' => 'Ophthalmic Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OTGEL' => ['display' => 'Otic Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPGEL' => ['display' => 'Topical Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'URETHGEL' => ['display' => 'Urethral Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGGEL' => ['display' => 'Vaginal Gel', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VGELAPL' => ['display' => 'Vaginal Gel with Applicator', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PASTE' => ['display' => 'Paste', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PUD' => ['display' => 'Pudding', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPASTE' => ['display' => 'Toothpaste', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SUSP' => ['display' => 'Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ITSUSP' => ['display' => 'Intrathecal Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OPSUSP' => ['display' => 'Ophthalmic Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORSUSP' => ['display' => 'Oral Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERSUSP' => ['display' => 'Extended-Release Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERSUSP12' => ['display' => '12 Hour Extended-Release Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERSUSP24' => ['display' => '24 Hour Extended Release Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'OTSUSP' => ['display' => 'Otic Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECSUSP' => ['display' => 'Rectal Suspension', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '_SolidDrugForm' => ['display' => 'Solid Drug Form', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'BAR' => ['display' => 'Bar', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'BARSOAP' => ['display' => 'Bar Soap', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'MEDBAR' => ['display' => 'Medicated Bar Soap', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CHEWBAR' => ['display' => 'Chewable Bar', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'BEAD' => ['display' => 'Beads', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CAKE' => ['display' => 'Cake', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CEMENT' => ['display' => 'Cement', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CRYS' => ['display' => 'Crystals', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DISK' => ['display' => 'Disk', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'FLAKE' => ['display' => 'Flakes', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'GRAN' => ['display' => 'Granules', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'GUM' => ['display' => 'Chewing Gum', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PAD' => ['display' => 'Pad', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'MEDPAD' => ['display' => 'Medicated Pad', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PATCH' => ['display' => 'Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPATCH' => ['display' => 'Transdermal Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPATH16' => ['display' => '16 Hour Transdermal Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPATH24' => ['display' => '24 Hour Transdermal Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPATH2WK' => ['display' => 'Biweekly Transdermal Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPATH72' => ['display' => '72 Hour Transdermal Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TPATHWK' => ['display' => 'Weekly Transdermal Patch', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PELLET' => ['display' => 'Pellet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'PILL' => ['display' => 'Pill', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CAP' => ['display' => 'Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORCAP' => ['display' => 'Oral Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ENTCAP' => ['display' => 'Enteric Coated Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERECAP' => ['display' => 'Extended Release Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERCAP' => ['display' => 'Extended Release Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERCAP12' => ['display' => '12 Hour Extended Release Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERCAP24' => ['display' => '24 Hour Extended Release Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERECCAP' => ['display' => 'Extended Release Enteric Coated Capsule', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERTAB' => ['display' => 'Extended Release Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TAB' => ['display' => 'Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORTAB' => ['display' => 'Oral Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'BUCTAB' => ['display' => 'Buccal Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SRBUCTAB' => ['display' => 'Sustained Release Buccal Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CAPLET' => ['display' => 'Caplet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CHEWTAB' => ['display' => 'Chewable Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'CPTAB' => ['display' => 'Coated Particles Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DISINTAB' => ['display' => 'Disintegrating Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'DRTAB' => ['display' => 'Delayed Release Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ECTAB' => ['display' => 'Enteric Coated Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERECTAB' => ['display' => 'Extended Release Enteric Coated Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERTAB' => ['display' => 'Extended Release Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERTAB12' => ['display' => '12 Hour Extended Release Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ERTAB24' => ['display' => '24 Hour Extended Release Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'ORTROCHE' => ['display' => 'Lozenge/Oral Troche', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SLTAB' => ['display' => 'Sublingual Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGTAB' => ['display' => 'Vaginal Tablet', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'POWD' => ['display' => 'Powder', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'TOPPWD' => ['display' => 'Topical Powder', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECPWD' => ['display' => 'Rectal Powder', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGPWD' => ['display' => 'Vaginal Powder', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SUPP' => ['display' => 'Suppository', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'RECSUPP' => ['display' => 'Rectal Suppository', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'URETHSUPP' => ['display' => 'Urethral suppository', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'VAGSUPP' => ['display' => 'Vaginal Suppository', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'SWAB' => ['display' => 'Swab', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'MEDSWAB' => ['display' => 'Medicated swab', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        'WAFER' => ['display' => 'Wafer', 'system' => 'http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm'],
        '738998008' => ['display' => 'Emulsion', 'system' => 'http://snomed.info/sct'],
        '763824009' => ['display' => 'Gas', 'system' => 'http://snomed.info/sct'],
        '442015005' => ['display' => 'Intrauterine dose form', 'system' => 'http://snomed.info/sct'],
        '385286003' => ['display' => 'Implant', 'system' => 'http://snomed.info/sct'],
        '385174007' => ['display' => 'Pessary', 'system' => 'http://snomed.info/sct'],
        '764296002' => ['display' => 'Prolonged-release', 'system' => 'http://snomed.info/sct'],
        '761877007' => ['display' => 'Effervescent tablet', 'system' => 'http://snomed.info/sct'],
        '421366001' => ['display' => 'Tablet for oral suspension', 'system' => 'http://snomed.info/sct'],
        '421701006' => ['display' => 'Tablet for conventional release oral solution', 'system' => 'http://snomed.info/sct'],
        '385057009' => ['display' => 'Film-coated tablet', 'system' => 'http://snomed.info/sct'],
        '385120001' => ['display' => 'Impregnated dressing', 'system' => 'http://snomed.info/sct'],
        '764772008' => ['display' => 'Prolonged-release vaginal ring', 'system' => 'http://snomed.info/sct'],
        '385292009' => ['display' => 'Vaginal dose form', 'system' => 'http://snomed.info/sct'],
        '419672006' => ['display' => 'Bottle - unit of product usage', 'system' => 'http://snomed.info/sct'],
    ];

    public array $medicationrequest_status_reason = [
        'altchoice' => 'Try another treatment first',
        'clarif' => 'Prescription requires clarification',
        'drughigh' => 'Drug level too high',
        'hospadm' => 'Admission to hospital',
        'labint' => 'Lab interference issues',
        'non-avail' => 'Patient not available',
        'preg' => 'Parent is pregnant/breast feeding',
        'salg' => 'Allergy',
        'sddi' => 'Drug interacts with another drug',
        'sdupther' => 'Duplicate therapy',
        'sintol' => 'Suspected intolerance',
        'surg' => 'Patient scheduled for surgery',
        'washout' => 'Waiting for old drug to wash out',
    ];

    public array $medication_requestdispense_category = [
        'inpatient' => 'Inpatient',
        'outpatient' => 'Outpatient',
        'community' => 'Community',
        'discharge' => 'Discharge',
    ];

    public array $course_of_therapy_type = [
        'continuous' => 'Continuous long term therapy',
        'acute' => 'Short course (acute) therapy',
        'seasonal' => 'Seasonal',
    ];

    public array $time_interval = [
        'ms' => 'milliseconds',
        's' => 'seconds',
        'min' => 'minutes',
        'h' => 'hours',
        'd' => 'days',
        'wk' => 'weeks',
        'mo' => 'months',
        'a' => 'years',
    ];

    public array $substitution_reason = [
        'E' => 'equivalent',
        'EC' => 'equivalent composition',
        'BC' => 'brand composition',
        'G' => 'generic composition',
        'TE' => 'therapeutic equivalence',
        'TB' => 'therapeutic brand',
        'TG' => 'therapeutic generic',
        'F' => 'formulary',
        'N' => 'none',
    ];

    public array $timing = [
        'BID' => 'twice a day',
        'TID' => 'three times a day',
        'QID' => 'four times a day',
        'AM' => 'morning',
        'PM' => 'evening',
        'QOD' => 'every other day',
        'Q1H' => 'every hour',
        'Q2H' => 'every 2 hours',
        'Q3H' => 'every 3 hours',
        'Q4H' => 'every 4 hours',
        'Q6H' => 'every 6 hours',
        'Q8H' => 'every 8 hours',
        'BED' => 'bedtime',
        'WK' => 'weekly',
        'MO' => 'monthly',
    ];

    public array $route_snomed = [
        697971008 => 'Arteriovenous fistula route',
        420254004 => 'Body cavity route',
        54471007 => 'Buccal route',
        417070009 => 'Caudal route',
        418162004 => 'Colostomy route',
        446105004 => 'Conjunctival route',
        448598008 => 'Cutaneous route',
        372449004 => 'Dental route',
        447964005 => 'Digestive tract route',
        372450004 => 'Endocervical route',
        372451000 => 'Endosinusial route',
        372452007 => 'Endotracheopulmonary route',
        417985001 => 'Enteral route',
        404820008 => 'Epidural route',
        764723001 => 'Epilesional route',
        420163009 => 'Esophagostomy route',
        372453002 => 'Extra-amniotic route',
        766790006 => 'Extracorporeal hemodialysis route',
        714743009 => 'Extracorporeal route',
        418743005 => 'Fistula route',
        418136008 => 'Gastro-intestinal stoma route',
        372454008 => 'Gastroenteral route',
        127490009 => 'Gastrostomy route',
        372457001 => 'Gingival route',
        419954003 => 'Ileostomy route',
        718329006 => 'Infiltration route',
        429817007 => 'Interstitial route',
        58731000052100 => 'Intestinal route',
        58100008 => 'Intra-arterial route',
        12130007 => 'Intra-articular route',
        419396008 => 'Intraabdominal route',
        372458006 => 'Intraamniotic route',
        404819002 => 'Intrabiliary route',
        419778001 => 'Intrabronchial route',
        372459003 => 'Intrabursal route',
        418821007 => 'Intracameral route',
        372460008 => 'Intracardiac route',
        418331006 => 'Intracartilaginous route',
        1078280005 => 'Intracatheter instillation route',
        372461007 => 'Intracavernous route',
        446540005 => 'Intracerebral route',
        420719007 => 'Intracerebroventricular route',
        372462000 => 'Intracervical route',
        58761000052107 => 'Intracholangiopancreatic route',
        418892005 => 'Intracisternal route',
        448492006 => 'Intracolonic route',
        418608002 => 'Intracorneal route',
        418287000 => 'Intracoronal route',
        372463005 => 'Intracoronary route',
        1259221004 => 'Intracorporus cavernosum route',
        418987007 => 'Intracranial route',
        372464004 => 'Intradermal route',
        876824003 => 'Intradialytic route',
        372465003 => 'Intradiscal route',
        417989007 => 'Intraductal route',
        418887008 => 'Intraduodenal route',
        445756007 => 'Intradural route',
        446407004 => 'Intraepicardial route',
        448077001 => 'Intraepidermal route',
        445752009 => 'Intraesophageal route',
        445768003 => 'Intragastric route',
        445754005 => 'Intragingival route',
        58751000052109 => 'Intraglandular route',
        445941009 => 'Intrahepatic route',
        447026006 => 'Intraileal route',
        448491004 => 'Intrajejunal route',
        372466002 => 'Intralesional route',
        445913005 => 'Intralingual route',
        37737002 => 'Intraluminal route',
        372467006 => 'Intralymphatic route',
        447121004 => 'Intramammary route',
        60213007 => 'Intramedullary route',
        445767008 => 'Intrameningeal route',
        711378007 => 'Intramural route',
        78421000 => 'Intramuscular route',
        418133000 => 'Intramyometrial route',
        711360002 => 'Intraneural route',
        372468001 => 'Intraocular route',
        417255000 => 'Intraosseous route',
        419631009 => 'Intraovarian route',
        445771006 => 'Intrapericardial route',
        38239002 => 'Intraperitoneal route',
        372469009 => 'Intrapleural route',
        58771000052103 => 'Intraportal route',
        419810008 => 'Intraprostatic route',
        420201002 => 'Intrapulmonary route',
        419231003 => 'Intrasinal route',
        418418000 => 'Intraspinal route',
        372470005 => 'Intrasternal route',
        418877009 => 'Intrasynovial route',
        418586008 => 'Intratendinous route',
        418947002 => 'Intratesticular route',
        72607000 => 'Intrathecal route',
        417950001 => 'Intrathoracic route',
        404818005 => 'Intratracheal route',
        447122006 => 'Intratumor route',
        418091004 => 'Intratympanic route',
        62226000 => 'Intrauterine route',
        445755006 => 'Intravascular route',
        418114005 => 'Intravenous central route',
        419993007 => 'Intravenous peripheral route',
        47625008 => 'Intravenous route',
        420287000 => 'Intraventricular route - cardiac',
        372471009 => 'Intravesical route',
        418401004 => 'Intravitreal route',
        127491008 => 'Jejunostomy route',
        420185003 => 'Laryngeal route',
        447081004 => 'Lower respiratory tract route',
        420204005 => 'Mucous fistula route',
        46713006 => 'Nasal route',
        420218003 => 'Nasoduodenal route',
        127492001 => 'Nasogastric route',
        418730005 => 'Nasojejunal route',
        372472002 => 'Ocular route',
        54485002 => 'Ophthalmic route',
        26643006 => 'Oral route',
        418441008 => 'Orogastric route',
        372473007 => 'Oromucosal route',
        418664002 => 'Oropharyngeal route',
        10547007 => 'Otic route',
        418851001 => 'Paracervical route',
        419165009 => 'Paravertebral route',
        428191002 => 'Percutaneous route',
        372474001 => 'Periarticular route',
        418722009 => 'Peribulbar route',
        447080003 => 'Peridural route',
        372475000 => 'Perineural route',
        447052000 => 'Periodontal route',
        420047004 => 'Periosteal route',
        419762003 => 'Peritendinous route',
        58811000052103 => 'Peritumoral route',
        418204005 => 'Periurethral route',
        58821000052106 => 'Posterior juxtascleral route',
        37161004 => 'Rectal route',
        447694001 => 'Respiratory tract route',
        418321004 => 'Retrobulbar route',
        372476004 => 'Subconjunctival route',
        34206005 => 'Subcutaneous route',
        419601003 => 'Subgingival route',
        66621000052103 => 'Sublabial route',
        1611000175109 => 'Sublesional route',
        37839007 => 'Sublingual route',
        419874009 => 'Submucosal route',
        416174007 => 'Suborbital route',
        58831000052108 => 'Subretinal route',
        419320008 => 'Subtendinous route',
        1254769004 => 'Suprachoroidal route',
        419894000 => 'Surgical cavity route',
        418813001 => 'Surgical drain route',
        6064005 => 'Topical route',
        419243002 => 'Transcervical route',
        45890007 => 'Transdermal route',
        446435000 => 'Transendocardial route',
        404815008 => 'Transmucosal route',
        446442000 => 'Transplacental route',
        447229005 => 'Transtracheal route',
        447227007 => 'Transtympanic route',
        418511008 => 'Transurethral route',
        419021003 => 'Tumor cavity route',
        419684008 => 'Ureteral route',
        90028008 => 'Urethral route',
        420168000 => 'Urostomy route',
        16857009 => 'Vaginal route',
    ];

    public array $route = [
        'implant' => 'Implant',
        'Inhal' => 'Inhalation',
        'Instill' => 'Instillation',
        'N' => 'Nasal',
        'O' => 'Oral',
        'P' => 'Parenteral',
        'R' => 'Rectal',
        'SL' => 'Sublingual/Buccal/Oromucosal',
        'TD' => 'Transdermal',
        'V' => 'Vaginal',
        'Inhal.powder' => 'Inhalation Powder',
        'Inhal.aerosol' => 'Inhalation Aerosol',
        'Inhal.solution' => 'Inhalation Solution',
        'urethral' => 'Urethral',
        'TD patch' => 'Transdermal Patch',
        'intravesical' => 'Intravesical',
        'Instill.solution' => 'Instillation Solution',
        'lamella' => 'Lamella',
        'oral aerosol' => 'Oral Aerosol',
        's.c. implant' => 'S.C. Implant',
        'ocular' => 'Ocular',
        'otic' => 'Otic',
        'cutaneous' => 'Cutaneous',
        'inj.subcutaneous' => 'Injection Subcutaneous',
        'inj.intramuscular' => 'Injection Intramuscular',
        'inj.intravenous' => 'Injection Intravenous',
        'inj.intrathecal' => 'Injection Intrathecal',
        'Chewing Gum' => 'Chewing Gum',
        'ointment' => 'Ointment',
        'stomatologic' => 'Stomatologic',
    ];

    public array $medication_admin_category = [
        'inpatient' => 'Inpatient',
        'outpatient' => 'Outpatient',
        'community' => 'Community',
    ];

    public array $reason_medication_given = [
        'a' => 'None',
        'b' => 'Given as Ordered',
        'c' => 'Emergency',
    ];

    public array $medication_statement_category = [
        'inpatient' => 'Inpatient',
        'outpatient' => 'Outpatient',
        'community' => 'Community',
        'patientspecified' => 'Patient Specified',
    ];

    public array $drug_therapy_status = [
        '182862001' => 'Drug not taken - dislike taste',
        '182863006' => 'Drug not taken - dislike form',
        '182864000' => 'Drug not taken - side-effects',
        '182865004' => 'Drug not taken - inconvenient',
        '182867007' => 'Drug not taken - pat disbelief',
        '182868002' => 'Treatment stopped - alternative therapy undertaken',
        '182869005' => 'Drug not taken - patient lost tablets',
        '182870006' => 'Drug discontinued - reason unknown',
        '182871005' => 'Drug discontinued - patient fear/risk',
        '182872003' => 'Drug discontinued - too expensive',
        '182873008' => 'Drug treatment stopped - patient ran out of tablets',
        '182874002' => 'Treatment stopped - patient unable to concentrate',
        '266711001' => 'Drug not taken - problem swallowing',
        '275929009' => 'Tablets too large to swallow',
        '134390006' => 'Angiotensin converting enzyme inhibitor not indicated',
        '134397009' => 'Angiotensin converting enzyme inhibitor declined',
        '135799002' => 'Angiotensin converting enzyme inhibitor indicated',
        '161646004' => 'H/O: high risk medication',
        '161647008' => 'H/O: anticoagulant therapy',
        '161648003' => 'H/O: steroid therapy',
        '161649006' => 'H/O: insulin therapy',
        '161650006' => 'H/O: anticonvulsant therapy',
        '161652003' => 'H/O: hormone replacement (HRT)',
        '161653008' => 'H/O: chemotherapy',
        '170622002' => 'Oral steroids started',
        '170624001' => 'Oral steroids stopped',
        '170688000' => 'Lithium stopped',
        '170689008' => 'Injectable phenothiazine stopped',
        '170821007' => 'B12 injections started',
        '170826002' => 'B12 injections stopped',
        '170919001' => 'Warfarin therapy stopped',
        '170954008' => 'Hormone replacement therapy (HRT) contraindicated',
        '170955009' => 'Hormone replacement therapy (HRT) started',
        '170958006' => 'Hormonal replacement therapy (HRT) stopped',
        '182834008' => 'Drug course completed',
        '182840001' => 'Drug treatment stopped - medical advice',
        '182841002' => 'Dr stopped drugs - ineffective',
        '182842009' => 'Doctor stopped drugs - side effect',
        '182843004' => 'Dr stopped drugs - inconvenient',
        '182844005' => 'Doctor stopped drugs - patient dislikes',
        '182845006' => 'Doctor stopped drugs - avoid interaction',
        '182846007' => 'Doctor stopped drugs - medical aim achieved',
        '274512008' => 'Drug therapy discontinued',
        '309841001' => 'Thyroxine treatment stopped',
        '312451002' => 'Aspirin prophylaxis contra-indicated',
        '315023008' => 'Aspirin prophylaxis refused',
        '315062004' => 'Beta blocker contraindicated',
        '315364008' => 'Angiotensin converting enzyme inhibitors contraindicated',
        '390914001' => 'Thrombolytic therapy refused',
        '391158008' => 'Antibiotic prophylaxis recommended',
        '391159000' => 'Antibiotic prophylaxis not recommended',
        '394888000' => 'Hormone replacement therapy requested',
        '394987009' => 'Angiotensin II receptor antagonists contraindicated',
        '395006008' => 'Medication stopped - interaction',
        '395007004' => 'Medication stopped - ineffective',
        '395008009' => 'Medication stopped - contra-indication',
        '395009001' => 'Medication stopped - side effect',
        '401084003' => 'Angiotensin II receptor antagonist declined',
        '401244004' => 'H/O: prolonged corticosteroid therapy',
        '407572003' => 'Angiotensin II receptor antagonist not indicated',
        '408339001' => 'Thrombolysis therapy not indicated',
        '408354007' => 'Drug treatment still needed',
        '408355008' => 'Drug treatment no longer needed',
        '412782003' => 'Inappropriate medication stopped',
        '413555000' => 'Antibiotic prophylaxis indicated',
        '413558003' => 'Anticoagulation contraindicated',
        '413559006' => 'Anticoagulation declined',
        '413560001' => 'Anticoagulation not indicated',
        '416404000' => 'Angiotensin converting enzyme inhibitor target dose not achieved',
        '417576009' => 'Deferred antibiotic therapy',
        '430279008' => 'Drug treatment stopped at end of clinical trial',
        '438553004' => 'H/O: drug therapy',
        '439631004' => 'H/O: statin therapy',
        '440935004' => 'H/O: beta blocker therapy',
        '440991005' => 'H/O: nitrate therapy',
        '441186000' => 'H/O: antiplatelet agent therapy',
        '441195008' => 'H/O: angiotensin converting enzyme (ACE) inhibitor therapy',
        '441196009' => 'H/O: angiotensin II receptor antagonist therapy',
        '441899004' => 'History of therapy with ototoxic medication',
        '473151000' => 'History of tuberculosis chemotherapy',
        '698428006' => 'Angiotensin II receptor antagonist indicated',
        '698449007' => 'Antibiotic therapy indicated',
        '698459008' => 'Antidepressant drug treatment stopped',
        '698460003' => 'Antiviral therapy declined',
        '698468005' => 'Bisoprolol contraindicated',
        '698758004' => 'Nebivolol therapy refused',
        '698985001' => 'Long term dual antiplatelet drug therapy indicated',
        '699008007' => 'History of fenfluramine therapy',
        '699137009' => 'Carvedilol therapy declined',
        '700110004' => 'Bisphosphonate prophylaxis suspended',
        '700384008' => 'Antibiotic prophylaxis not indicated',
        '702542006' => 'Incretin mimetic therapy started',
        '703989007' => 'Teriparatide therapy declined',
        '703991004' => 'Raloxifene therapy declined',
        '703996009' => 'Teriparatide not indicated',
        '703997000' => 'Teriparatide contraindicated',
        '703999002' => 'Raloxifene contraindicated',
        '704000000' => 'Raloxifene not indicated',
        '704033005' => 'Phosphodiesterase 5 inhibitor not indicated',
        '704047009' => 'Phosphodiesterase 5 inhibitor declined',
        '707298000' => 'Phosphodiesterase-5 inhibitor contraindicated',
        '708000007' => 'Insulin treatment stopped',
        '710159007' => 'Long-term current use of immunosuppressive drug',
        '710814002' => 'Long-term current use of drug therapy',
        '710815001' => 'Long-term current use of insulin',
        '710816000' => 'Long-term current use of steroid',
        '710817009' => 'Long-term current use of inhaled steroid',
        '711149003' => 'Long-term current use of antibiotic',
        '711150003' => 'Long-term current use of anticoagulant',
        '711370000' => 'Oral steroids used since last encounter',
        '711436000' => 'Inhaled steroids used daily',
        '712985002' => 'Chemotherapy not done',
        '106511000119106' => 'Long-term current use of mycophenolate',
        '106521000119104' => 'Long-term current use of cyclophosphamide',
        '106631000119102' => 'Long-term current use of infliximab',
        '106691000119103' => 'Long-term current use of etanercept',
        '133621000119103' => 'Long term current use of non-steroidal anti-inflammatory drug',
        '134651000119108' => 'History of estrogen therapy',
        '134671000119104' => 'History of systemic steroid therapy',
        '140561000119102' => 'Long-term current use of azathioprine',
    ];
}
